# Generated by Django 3.0.5 on 2020-10-30 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 10, 30, 7, 6, 48, 210294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 10, 30, 7, 6, 48, 225911, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 10, 30, 7, 6, 48, 210294, tzinfo=utc)),
        ),
    ]
